sudo: required

language: php

services:
  - docker
  - git

before_install:
- docker pull deferdie/php:latest
- docker run --rm -it deferdie/php:latest composer

script:
- docker run --rm deferdie/php:latest composer create-project --prefer-dist laravel/laravel test "5.6.* && ls -la"