sudo: required

language: php

services:
  - docker
  - git

before_install:
- docker pull deferdie/php:latest
- docker run --rm -it deferdie/php:latest composer

script:
- composer create-project --prefer-dist laravel/laravel test "5.6.*"
- cd test && composer install && php artisan